import { useEffect, useMemo, useState } from 'react';
import { Save, Loader2, Check, AlertTriangle } from 'lucide-react';
import type { Crate, EntityPatch } from '@/shared/types';
import { Field, TextInput, TextArea, LinkMultiSelect, type LinkOption } from './FormControls';
import { asIdList, authorText, displayType, EDITABLE_LINK_FIELDS, keywordList, type EditableLinkField } from './entityUtils';

const LINK_LABELS: Record<EditableLinkField, string> = {
  usedDataset: 'Used datasets',
  usedSoftware: 'Used software',
  generatedBy: 'Generated by',
  derivedFrom: 'Derived from',
  generated: 'Generated',
};

type LinkState = Record<EditableLinkField, string[]>;

/** Edit the editable metadata of one existing entity, persisted via updateEntity. */
export function EditEntityForm({
  dir,
  crate,
  entityId,
  onSaved,
}: {
  dir: string;
  crate: Crate;
  entityId: string;
  onSaved: (updated: Crate) => void;
}) {
  const entity = useMemo(
    () => crate['@graph'].find((e) => String(e['@id']) === entityId),
    [crate, entityId],
  );

  const linkOptions: LinkOption[] = useMemo(
    () =>
      crate['@graph']
        .filter((e) => String(e['@id']) !== entityId && !String(e['@id']).endsWith('ro-crate-metadata.json'))
        .map((e) => ({ id: String(e['@id']), name: e.name?.toString() || String(e['@id']), type: displayType(e['@type']) })),
    [crate, entityId],
  );

  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [version, setVersion] = useState('');
  const [author, setAuthor] = useState('');
  const [keywords, setKeywords] = useState('');
  const [links, setLinks] = useState<LinkState>({ usedDataset: [], usedSoftware: [], generatedBy: [], derivedFrom: [], generated: [] });
  const [original, setOriginal] = useState<LinkState>({ usedDataset: [], usedSoftware: [], generatedBy: [], derivedFrom: [], generated: [] });
  const [saving, setSaving] = useState(false);
  const [status, setStatus] = useState<'idle' | 'saved' | 'error'>('idle');

  // (Re)initialize the form whenever the selected entity changes.
  useEffect(() => {
    if (!entity) return;
    setName(entity.name?.toString() ?? '');
    setDescription(entity.description?.toString() ?? '');
    setVersion(entity.version != null ? String(entity.version) : '');
    setAuthor(authorText(entity.author));
    setKeywords(keywordList(entity.keywords).join(', '));
    const init = {} as LinkState;
    for (const f of EDITABLE_LINK_FIELDS) init[f] = asIdList(entity[f]);
    setLinks(init);
    setOriginal(init);
    setStatus('idle');
  }, [entity]);

  if (!entity) {
    return <p className="text-sm text-muted-foreground">Select an entity in Explore to edit it.</p>;
  }

  async function save() {
    setSaving(true);
    setStatus('idle');
    const patch: EntityPatch = {
      name,
      description,
      version,
      author,
      keywords: keywordList(keywords),
      links: {},
    };
    // Only write link fields the user touched or that previously existed (avoid adding empty keys).
    for (const f of EDITABLE_LINK_FIELDS) {
      if (links[f].length > 0 || original[f].length > 0) patch.links![f] = links[f];
    }
    const updated = await window.fairscape.updateEntity(dir, entityId, patch);
    setSaving(false);
    if (updated) {
      setStatus('saved');
      onSaved(updated);
    } else {
      setStatus('error');
    }
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2">
        <span className="inline-flex items-center rounded-md bg-primary/15 px-2 py-0.5 text-xs font-medium text-primary">
          {displayType(entity['@type'])}
        </span>
        <span className="break-all font-mono text-xs text-muted-foreground">{entityId}</span>
      </div>

      <Field label="Name">
        <TextInput value={name} onChange={setName} />
      </Field>
      <Field label="Description">
        <TextArea value={description} onChange={setDescription} rows={4} />
      </Field>
      <div className="grid grid-cols-2 gap-4">
        <Field label="Version">
          <TextInput value={version} onChange={setVersion} placeholder="e.g. 1.0" />
        </Field>
        <Field label="Author">
          <TextInput value={author} onChange={setAuthor} />
        </Field>
      </div>
      <Field label="Keywords" hint="Comma-separated.">
        <TextInput value={keywords} onChange={setKeywords} placeholder="ecg, hrv, atrial fibrillation" />
      </Field>

      <div className="space-y-3 border-t border-border pt-4">
        <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Relationships</p>
        {EDITABLE_LINK_FIELDS.map((f) => (
          <LinkMultiSelect
            key={f}
            label={LINK_LABELS[f]}
            options={linkOptions}
            value={links[f]}
            onChange={(ids) => setLinks((prev) => ({ ...prev, [f]: ids }))}
          />
        ))}
      </div>

      <div className="flex items-center gap-3 border-t border-border pt-4">
        <button
          onClick={() => void save()}
          disabled={saving}
          className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition hover:opacity-90 disabled:opacity-40"
        >
          {saving ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}
          Save changes
        </button>
        {status === 'saved' && (
          <span className="inline-flex items-center gap-1.5 text-sm text-success">
            <Check className="size-4" /> Saved &amp; validated
          </span>
        )}
        {status === 'error' && (
          <span className="inline-flex items-center gap-1.5 text-sm text-destructive">
            <AlertTriangle className="size-4" /> Could not write changes
          </span>
        )}
      </div>
    </div>
  );
}
