// Pure renderer helpers for the Crate Workspace. No electron/node imports — the
// crate is loaded once via window.fairscape.readCrate() and walked in the renderer.
import type { Crate, CrateEntity } from '@/shared/types';

/** Relationship fields we surface as clickable links, in display order. */
export const RELATIONSHIP_FIELDS: { key: string; label: string }[] = [
  { key: 'generatedBy', label: 'Generated by' },
  { key: 'generated', label: 'Generated' },
  { key: 'usedDataset', label: 'Used datasets' },
  { key: 'usedSoftware', label: 'Used software' },
  { key: 'usedSample', label: 'Used samples' },
  { key: 'usedInstrument', label: 'Used instruments' },
  { key: 'usedByComputation', label: 'Used by computations' },
  { key: 'derivedFrom', label: 'Derived from' },
  { key: 'hasPart', label: 'Has parts' },
  { key: 'isPartOf', label: 'Part of' },
  { key: 'schema', label: 'Schema' },
];

/** The relationship keys an EntityPatch may write back (subset of the above). */
export const EDITABLE_LINK_FIELDS = ['usedDataset', 'usedSoftware', 'generatedBy', 'derivedFrom', 'generated'] as const;
export type EditableLinkField = (typeof EDITABLE_LINK_FIELDS)[number];

/** Normalize an @type (which may be a string or array, prefixed) to a friendly label. */
export function displayType(type: CrateEntity['@type']): string {
  const types = Array.isArray(type) ? type : type ? [type] : [];
  // Prefer the EVI-specific type over generic prov:* / schema.org wrappers.
  const preferred =
    types.find((t) => /EVI#|evi:/i.test(t)) ?? types.find((t) => !/^prov:|schema\.org/i.test(t)) ?? types[0];
  if (!preferred) return 'Other';
  const tail = String(preferred).split(/[#/:]/).pop() ?? String(preferred);
  return tail || 'Other';
}

/** Coerce a relationship value (`{'@id'} | [{'@id'}] | string | string[]`) to an @id list. */
export function asIdList(value: unknown): string[] {
  if (value == null) return [];
  const arr = Array.isArray(value) ? value : [value];
  return arr
    .map((v) => {
      if (typeof v === 'string') return v;
      if (v && typeof v === 'object' && '@id' in v) return String((v as { '@id': unknown })['@id']);
      return null;
    })
    .filter((v): v is string => !!v);
}

/** Index the @graph by @id for O(1) link resolution. */
export function byId(crate: Crate | null): Map<string, CrateEntity> {
  const m = new Map<string, CrateEntity>();
  for (const e of crate?.['@graph'] ?? []) if (e['@id']) m.set(String(e['@id']), e);
  return m;
}

/** Human label for an entity id (its name, falling back to the id itself). */
export function entityName(index: Map<string, CrateEntity>, id: string): string {
  return index.get(id)?.name?.toString() || id;
}

/** Normalize keywords (string or array) to an array of trimmed strings. */
export function keywordList(keywords: CrateEntity['keywords']): string[] {
  if (!keywords) return [];
  const arr = Array.isArray(keywords) ? keywords : String(keywords).split(',');
  return arr.map((k) => String(k).trim()).filter(Boolean);
}

/** Author may be a string, a ref, or a list — render it as a readable string. */
export function authorText(author: CrateEntity['author']): string {
  if (!author) return '';
  const arr = Array.isArray(author) ? author : [author];
  return arr
    .map((a) => (typeof a === 'string' ? a : a && typeof a === 'object' && '@id' in a ? String(a['@id']) : ''))
    .filter(Boolean)
    .join(', ');
}

/** Resolved outbound links for an entity, grouped by relationship label. */
export interface EntityLink {
  label: string;
  key: string;
  targets: { id: string; name: string }[];
}

export function entityLinks(entity: CrateEntity, index: Map<string, CrateEntity>): EntityLink[] {
  const out: EntityLink[] = [];
  for (const { key, label } of RELATIONSHIP_FIELDS) {
    const ids = asIdList(entity[key]);
    if (ids.length) out.push({ label, key, targets: ids.map((id) => ({ id, name: entityName(index, id) })) });
  }
  return out;
}

/** Strip `file://` and leading slashes, normalize `\`→`/` — to compare crate paths to scan paths. */
function normalizePath(p: string): string {
  return p.replace(/^file:\/\//, '').replace(/\\/g, '/').replace(/^\/+/, '');
}

/**
 * The set of crate-relative file paths already registered, derived from each entity's
 * `contentUrl`. Used to mark scanned files as registered vs. pending in the Files tab.
 */
export function registeredPaths(crate: Crate | null): Set<string> {
  const set = new Set<string>();
  for (const e of crate?.['@graph'] ?? []) {
    const url = e.contentUrl;
    if (typeof url === 'string' && url) set.add(normalizePath(url));
  }
  return set;
}

/** Turn a file path into a human title: basename minus extension, `_`/`-` → space. */
export function fileNameToTitle(filePath: string): string {
  const base = filePath.split('/').pop() ?? filePath;
  const dot = base.lastIndexOf('.');
  const stem = dot > 0 ? base.slice(0, dot) : base;
  return stem.replace(/[_-]+/g, ' ').trim();
}

/** Entities grouped by display type, each group sorted by name, groups sorted by name. */
export function groupByType(crate: Crate | null): { type: string; entities: CrateEntity[] }[] {
  const groups = new Map<string, CrateEntity[]>();
  for (const e of crate?.['@graph'] ?? []) {
    // Skip the metadata descriptor node — it's plumbing, not a real entity.
    if (String(e['@id']).endsWith('ro-crate-metadata.json')) continue;
    const t = displayType(e['@type']);
    const bucket = groups.get(t);
    if (bucket) bucket.push(e);
    else groups.set(t, [e]);
  }
  return [...groups.entries()]
    .map(([type, entities]) => ({
      type,
      entities: entities.sort((a, b) => (a.name?.toString() ?? '').localeCompare(b.name?.toString() ?? '')),
    }))
    .sort((a, b) => a.type.localeCompare(b.type));
}
